version: '3'
services:
  server:
    build: server/
    volumes:
      - ./server:/server
    container_name: 'server'
    command: python ./server.py
    ports:
      - 1244:1234
  client:
    build: client/
    container_name: 'client'
    command: python ./client.py
    network_mode: host
    depends_on:
      - server